let dados = [
    {
    epoca : "Paleolítico",
    descricao : "A descoberta do fogo e o desenvolvimento pelos humanos de ferramentas de pedra foram duas das primeiras e mais importantes tecnologias desenvolvidas pela humanidade, o domínio de ambos marcou pontos importantes na evolução da raça humana até os dias de hoje.  As primeiras ferramentas de pedra, criadas há mais de 2,5 milhões de anos, permitiram que os humanos lascassem pedras para criar lâminas e bordas afiadas, que eram usadas para caçar e fabricar outras ferramentas.   Ao mesmo tempo, o fogo, descoberto possivelmente a partir de incêndios naturais causados por raios ou erupções vulcânicas, foi dominado pelos humanos, inicialmente apenas mantido aceso, e posteriormente produzido com a ajuda dessas mesmas ferramentas assim, o domínio do fogo e das ferramentas de pedra andou lado a lado. Entre 1,5 milhão e 400 mil anos atrás, os humanos começaram a dominar o fogo, uma tecnologia que, somada ao uso das ferramentas de pedra, foi essencial para sobreviver ao frio extremo e permitir a ocupação de novas regiões. O fogo ofereceu calor, luz e proteção, enquanto as ferramentas aprimoradas de pedra eram usadas para caçar e processar alimentos. Quando o fogo começou a ser utilizado para cozinhar, as ferramentas de pedra foram fundamentais para cortar e preparar os alimentos. Isso levou a uma dieta mais nutritiva e variada, que, por sua vez, impulsionou o desenvolvimento cerebral e a saúde de nossos ancestrais.",
    link : "https://brasilescola.uol.com.br/historiag/paleolitico.htm"
},    
    {
      epoca: "Paleolítico Superior",
      descricao: "Durante o Paleolítico Superior (50.000 a 12.000 anos atrás) houve um notável desenvolvimento tecnológico que transformou profundamente a vida da raça humana No Paleolítico Superior, as ferramentas de pedra ficaram mais sofisticadas. Com lâminas finas, os humanos conseguiram explorar novas fontes de alimento e recursos de maneira mais eficiente. A utilização de osso e chifre para fabricar ferramentas e armas, como agulhas para costurar roupas e arpões para a pesca, ampliou ainda mais a capacidade dos humanos de adaptar seu ambiente e melhorar suas técnicas de caça e pesca. A arte rupestre surgiu como forma de expressão cultural, com paredes de cavernas usadas para retratar crenças e conhecimentos. O desenvolvimento de novas técnicas e ferramentas, como a criação de pigmentos a partir de minerais e plantas, e o uso de ferramentas de pedra para gravar, permitiu uma maior complexidade e diversidade nas representações artísticas. Essas inovações tecnológicas facilitaram a criação de arte mais detalhada e duradoura. A tecnologia, transformou a maneira como os humanos pré-históricos criavam arte e também como eles comunicavam e preservavam suas experiências e conhecimentos. A expressão artística através da arte rupestre e das esculturas também revelou uma rica capacidade de comunicação e simbolismo, refletindo uma complexidade cognitiva que antes se acreditava exclusiva dos humanos modernos. O processamento de peles levou ao desenvolvimento de roupas melhores, proporcionando uma maior proteção contra o frio. A construção de abrigos mais elaborados, como cabanas e tendas, e a utilização de cavernas como habitações proporcionaram maior proteção contra predadores.O domínio do fogo, já iniciado no Paleolítico Médio, permitiu cozinhar alimentos, aquecer-se durante o inverno, afastar animais predadores e iluminar as noites, além de possibilitar o desenvolvimento de novas tecnologias e técnicas.A sedentarização tornou-se mais viável com a construção de abrigos sofisticados e o domínio do fogo, permitindo que os grupos humanos se estabelecessem em locais por períodos mais longos e abandonassem o nomadismo constante. A vida em grupos mais estáveis favoreceu o desenvolvimento social, criando relações mais complexas, mitos e crenças compartilhadas, além da especialização de tarefas. As novas tecnologias permitiram a expansão territorial.",

      link: "https://seu_link_para_o_paleolitico_superior"
    },

    {/// Periodo Mesolítico: A Transição para um Novo Modo de Vida
        epoca: "Mesolítico",
        descricao: "Com o fim do Paleolítico dá-se início ao Mesolítico(cerca de 12.000 a 8.000 anos atrás), a humanidade enfrentou grandes mudanças tecnológicas e sociais, impulsionadas pelo fim da última era glacial. O derretimento das geleiras transformou o ambiente, substituindo estepes por florestas densas, e forçou os grupos humanos a adaptarem suas práticas de subsistência. Surgiram novas tecnologias de caça e pesca, com o desenvolvimento de micrólitos, pequenas lâminas de pedra fixadas em hastes para criar armas mais eficazes. A pesca tornou-se crucial nesse período, levando ao desenvolvimento de ferramentas como anzóis e redes, bem como de canoas rudimentares. Além disso, o armazenamento de alimentos tornou-se uma prática mais comum, possibilitando a formação de assentamentos mais permanentes, embora muitas sociedades ainda fossem nômades. O impacto dessas tecnologias estendeu-se à organização social e à vida cultural. As sociedades começaram a se estruturar ao redor de áreas férteis. Com a melhoria na disponibilidade de alimentos, houve mais tempo para atividades como a produção de artefatos simbólicos e ferramentas mais sofisticadas. Evidências arqueológicas indicam um aumento nas práticas rituais, como sepultamentos com oferendas e arte rupestre em locais ao ar livre, sugerindo uma crescente complexidade nas crenças e nos costumes espirituais. Grupos começaram a experimentar o cultivo e a criação de animais, criando as bases para a Revolução Neolítica. Ferramentas simples, como bastões para arar o solo, ajudaram no plantio de grãos selvagens, uma prática que futuramente levaria à agricultura, a tecnologia no Mesolítico não só aprimorou a subsistência humana, mas também transformou profundamente a organização social",
        link: "https://brasilescola.uol.com.br/historiag/periodo-mesolitico.htm#:~:text=da%20Pr%C3%A9%2DHist%C3%B3ria-,Divis%C3%A3o%20do%20Per%C3%ADodo%20Mesol%C3%ADtico,e%20que%20antecede%20o%20Neol%C3%ADtico."
      }, 
      
      

///Tecnologia e Cultura no Neolítico: Ferramentas e Artefatos
    {   epoca : "Neolitico",
        descricao : "O Neolítico, ou Idade da Pedra Polida, marca um ponto de inflexão na história da humanidade, caracterizado por profundas transformações nas formas de vida e nas relações sociais. A tecnologia, nesse período, desempenhou um papel central, impulsionando a transição de sociedades nômades de caçadores-coletores para comunidades agrícolas sedentárias.Uma das principais inovações tecnológicas do Neolítico foi o desenvolvimento da agricultura. A domesticação de plantas e animais permitiu o cultivo de alimentos de forma sistemática, garantindo uma fonte de subsistência mais estável. Ferramentas como enxadas, foices e machados de pedra polida tornaram a agricultura mais eficiente, possibilitando a produção de excedentes alimentares. Essa abundância de alimentos sustentou o crescimento populacional e a formação de aldeias permanentes. A cerâmica também foi uma invenção crucial. A produção de vasos e outros utensílios de cerâmica permitiu o armazenamento de alimentos, a preparação de refeições mais elaboradas e o desenvolvimento de técnicas de fermentação. A cerâmica também foi utilizada para fins rituais e artísticos, evidenciando a complexidade cultural das sociedades neolíticas. A construção de habitações mais sólidas, como casas de taipa e palafitas, e a organização de aldeias com ruas e praças demonstram um aumento na complexidade social. A divisão do trabalho, com a especialização de tarefas, e a criação de sistemas de troca e comércio contribuíram para o fortalecimento dos laços sociais e o desenvolvimento de novas formas de organização social. A religião e a espiritualidade também se tornaram mais complexas no Neolítico. A construção de monumentos megalíticos, como os menires e os dólmens, sugere a existência de crenças religiosas elaboradas e a realização de rituais coletivos. A arte, expressa através da pintura rupestre e da criação de objetos ornamentados, reflete a rica vida espiritual das comunidades neolíticas."
    },
    ///A Idade dos Metais: Ferramentas, Escrita e o Nascer das Civilizações

    {   epoca : "Idade dos Metais",
        descricao: "A Idade dos Metais representa um marco crucial na evolução humana, caracterizada pela transição do uso de ferramentas de pedra para a utilização de metais como cobre, bronze e ferro. Essa mudança tecnológica proporcionou um salto significativo na capacidade humana de moldar o ambiente e desenvolver sociedades mais complexas.As ferramentas de metal, mais resistentes e versáteis que as de pedra, revolucionaram a agricultura, a caça e a construção. A enxada de metal, por exemplo, permitiu o cultivo de áreas maiores e mais profundas, aumentando a produção de alimentos. As armas de metal, como espadas e lanças, tornaram os conflitos mais eficazes, influenciando a organização social e a formação de estados.Paralelamente ao desenvolvimento metalúrgico, outro fator crucial para a complexificação das sociedades foi o surgimento da escrita. A necessidade de registrar informações sobre comércio, agricultura, leis e genealogias impulsionou o desenvolvimento de símbolos e códigos para representar ideias e sons. A escrita, inicialmente pictográfica, evoluiu para sistemas mais complexos, como a cuneiforme na Mesopotâmia e os hieróglifos no Egito.A escrita permitiu a transmissão do conhecimento de geração em geração, a criação de leis e códigos de conduta, o desenvolvimento da literatura e da filosofia. A burocracia, a contabilidade e a administração se tornaram mais eficientes, possibilitando o surgimento de estados mais complexos e organizados.Com o domínio da metalurgia e o desenvolvimento da escrita, a humanidade deu um passo fundamental rumo à civilização. A Idade dos Metais marca o fim da Pré-História e a transição para a Idade Antiga, um período caracterizado pelo surgimento de cidades, estados complexos, sistemas de escrita e a organização de grandes impérios. A metalurgia e a escrita, portanto, foram os principais motores das transformações sociais, econômicas e culturais que moldaram o mundo em que vivemos hoje.",
        link : "https://brasilescola.uol.com.br/historiag/idade-antiga.htm"

    },

    {
        epoca: "Idade Antiga",
        descricao: "A Idade Antiga foi marcada pelo surgimento das primeiras civilizações, como a Mesopotâmia, o Egito Antigo e a Grécia Antiga. Nesse período, ocorreram avanços significativos na agricultura, na escrita, na arquitetura e na organização social. A invenção da roda e a construção de grandes monumentos, como as pirâmides egípcias, são exemplos das inovações tecnológicas da época.",
        link: "https://brasilescola.uol.com.br/historiag/idade-antiga.htm"
    },
    {
        epoca: "Idade Média",
        descricao: "A Idade Média foi um período histórico marcado pelo feudalismo e pela influência da Igreja Católica. Apesar das crenças populares, houve avanços significativos em áreas como a agricultura, a arquitetura e a medicina. A invenção da prensa móvel por Gutenberg revolucionou a comunicação e a disseminação do conhecimento.",
        link: "https://brasilescola.uol.com.br/historiag/idade-media.htm"
    },
    {
        epoca: "Idade Moderna",
        descricao: "A Idade Moderna foi marcada por grandes transformações, como as Grandes Navegações, a Reforma Protestante e a Revolução Industrial. A invenção da máquina a vapor e o desenvolvimento da ciência moderna foram cruciais para o desenvolvimento da sociedade industrial.",
        link: "https://brasilescola.uol.com.br/historiag/idade-moderna.htm"
    },
    {
        epoca: "Idade Contemporânea",
        descricao: "A Idade Contemporânea é caracterizada pela rápida evolução tecnológica, pela globalização e pelas grandes guerras mundiais. A invenção do computador e a internet revolucionaram a comunicação e a forma como vivemos.",
        link: "https://brasilescola.uol.com.br/historiag/idade-contemporanea.htm"
    }
 

];
